# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-10 11:28
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='Update Bio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(default='no photo', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
