# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-11 09:28
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.TextField(default='comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(default='imagepath', max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_caption',
            field=models.CharField(default='caption', max_length=144),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='image_name',
            field=models.CharField(default='name', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='likes',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default='2004-10-19 10:23:54+02'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
