# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_auto_20210710_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default='2021-07-05 09:26:03.720347+03'),
            preserve_default=False,
        ),
    ]
