# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-07-10 15:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_image_posted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='NgetichNick', max_length=30),
            preserve_default=False,
        ),
    ]
