# Generated by Django 3.2 on 2021-07-12 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user',
            new_name='liker',
        ),
    ]
